# Generated by Django 3.2 on 2021-05-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_init"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatsecretuser",
            name="authorize_url",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="fatsecretuser",
            name="pin",
            field=models.IntegerField(
                blank=True, default=None, max_length=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fatsecretuser",
            name="session_token",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
