# Generated by Django 3.2 on 2021-05-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210505_1413"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fatsecretuser",
            name="users_fatse_session_b12cdc_idx",
        ),
        migrations.RenameField(
            model_name="fatsecretuser",
            old_name="session_token",
            new_name="access_token",
        ),
        migrations.AddField(
            model_name="fatsecretuser",
            name="access_token_secret",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
