# Generated by Django 3.2 on 2021-05-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_added_access_token_secret_for_fatsecret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatsecretuser",
            name="pin",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
