# Generated by Django 3.2 on 2021-04-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Serving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_units", models.FloatField(null=True)),
                ("calories", models.FloatField(null=True)),
                ("protein", models.FloatField(null=True)),
                ("carbohydrate", models.FloatField(null=True)),
                ("fat", models.FloatField(null=True)),
                ("trans_fat", models.FloatField(null=True)),
                ("saturated_fat", models.FloatField(null=True)),
                ("monounsaturated_fat", models.FloatField(null=True)),
                ("polyunsaturated_fat", models.FloatField(null=True)),
                ("cholesterol", models.FloatField(null=True)),
                ("fiber", models.FloatField(null=True)),
                ("calcium", models.FloatField(null=True)),
                ("iron", models.FloatField(null=True)),
                ("potassium", models.FloatField(null=True)),
                ("sodium", models.FloatField(null=True)),
                ("sugar", models.FloatField(null=True)),
                ("vitamin_a", models.FloatField(null=True)),
                ("vitamin_c", models.FloatField(null=True)),
            ],
        ),
    ]
