name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: "(+u!m%s#e@r!i9$9&-c-5)ft22s-)tth4sj=)o1v=z8h%axq$a"
      DATABASE_URL: "sqlite:///db.sqlite"
      REDIS_URL: "redis://redis:6379"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Test with pytest
      run: |
        cd src && pytest
